apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rube-goldberg

resources:
  - 00-namespace.yaml
  - 01-configmaps-secrets.yaml
  - 02-infrastructure.yaml
  - 03-microservices.yaml
