FROM eclipse-temurin:26-jre-alpine
ARG JAR_FILE
WORKDIR /app
COPY ${JAR_FILE} app.jar
ENV JAVA_TOOL_OPTIONS="-Xms128m -Xmx384m"
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "app.jar"]
